spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: checkout
    password: checkout
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          #        default_schema: checkout
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
          use_sql_comments: true
          jdbc:
            lob:
              non_contextual_creation: true